zxc=float(input())
asd=float(input())
resultat=zxc+asd
print(resultat)
resultat=zxc-asd
print(resultat)
resultat=zxc*asd
print(resultat)
resultat=zxc/asd
print(resultat)
resultat=zxc**asd
print(resultat)
resultat=zxc%asd
print(resultat)
resultat=zxc//asd
print(resultat)